C
C    THIS ROUTINE READS THE RESIDUE FILE AND PREAPRES THE TECPLOT FILES
C    FOR PLOTTING THE RESIDUES OF EACH EQUATION ON A SEMI-LOG SCALE
C

      DIMENSION RES(11)
      
      OPEN(UNIT=27,FILE='RESID')
      OPEN(UNIT=26,FILE='RESINP.DAT')
      OPEN(UNIT=28,FILE='TECRES.DAT')

      WRITE(28,*)'TITLE = "RESIDUES"'
      WRITE(28,*)'VARIABLES =ITER,CONT,UMOM,VMOM,TEMP'
           

      READ(26,*) 
      READ(26,*) ITMAX
      READ(27,*)
      
      DO I=1,ITMAX
      READ(27,*) II,(RES(J),J=1,11)
      WRITE(28,123) I, RES(1),RES(2),RES(3), RES(11)
      END DO

123   FORMAT(I4,5E15.6)

      CLOSE(26)
      CLOSE(27)
      CLOSE(28)

      STOP
      END
